// All the Static strings values which are used in Application

export const AppStrings = {
  Client_SignUp: 'Client Signup',
  Email: 'Email',
  Enter_Email: 'Enter Email...',
  Password: 'Password',
  Enter_Password: 'Enter Password...',
  Full_Name: 'Full Name',
  Enter_Full_Name: 'Enter Full Name...',
  SignUp: 'SIGNUP',
  Already_Have_Account: 'ALREADY HAVE AN ACCOUNT?',
  Login: 'LOGIN',
  Forget_Password: 'FORGET PASSWORD?',
  Forget_Password2: 'FORGET PASSWORD',
  Not_Have_Account: 'DON`T HAVE AN ACCOUNT?',
  Login2: 'Log In',
  Welcome_Text: 'Elevate Your Idea',
  Welcome_Sub_Text: '(With a Startup Coach!)',
  Create_Client_Account: 'CREATE CLIENT ACCOUNT',
  Create_Coach_Account: 'CREATE COACH ACCOUNT',
  Profile_Steup: 'Profile Setup',
  Profile_Picture: 'Profile Picture',
  Phone_Number: 'Phone Number',
  Enter_Phone_Number: 'Enter Phone Number...',
  Complete_Setup: 'COMPLETE SETUP',
  Create_Coach_Account2: 'Create Coach Account',
  Select_Image: 'Choose Image',
  Background_Information: 'Background Information',
  Background_Information_Header:
    'Please answer the following questions so that we can get a better idea of who you are, where you come from, and how you live.',
  Enter_Here: 'Enter Here...',
  Next: 'Next',
  Imapact_Social_Media: 'Impact of Social Media',
  Imapact_Social_Media_Header_One:
    'In the past 14 days, after exposure to social media content, have you experienced any of the following ?',
  Imapact_Social_Media_Header_Two: 'Please answer to the best of your ability.',
  Home: 'Home',
  Blog: 'Blog',
  Directory: 'Directory',
  Chat: 'Chat',
  Profile: 'Profile',
  Submit: 'SUBMIT',
  Forget_Password_Header:
    'Enter your email for the verification proccesss, we will send 4 digits code to your email.',
  New_Password: 'New Password',
  Enter_New_Password: 'Enter New Password...',
  Re_New_Password: 'Re-New Password',
  Re_Enter_New_Password: 'Re-Enter New Password...',
  Send: 'SEND',
  Verify: 'VERIFY',
  Enter_Four_Digit_Code: 'Enter 4 Digits Code',
  Four_Digit_Code_Header:
    'Enter the 4 digits code that you received on your email.',
  Reset_Password: 'Reset Password',
  Reset_Password_Header:
    'Set the new password for your account so you can login and access all the features.',
  Update_Passeword: 'Update Password',
  Okay: 'OKAY',
  Social_Media: ' SOCIAL MEDIA ',
  Case_Management: 'CASE MANAGEMENT',
  Therapist: "You're a Therapist!",
  Go_To_Admin_View: 'GO TO ADMIN VIEW',
  List_Empty_Text: 'Something went wrong...',
  Activity_Category_Name: 'Activity Category Name',
  Message: 'Message',
  Message_Text: 'Message Text',
};

export default AppStrings;
